version: "3"
services:
  web_dev:
    image: ijuniorfu/web_dev_ubuntu
    privileged: true
    ports:
      - "80:80"
      - "443:443"
      - "2222:22"
      - "9527:9527"
    volumes:
      - ${HTDOCS_DIR}:/data/htdocs
      - ${DOCKER_COMPOSE_CONF_DIR}/nginx/conf.d:/etc/nginx/conf.d
      - ${DOCKER_COMPOSE_CONF_DIR}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${DOCKER_COMPOSE_CONF_DIR}/php/php.ini:/etc/php.ini
      - ${DOCKER_COMPOSE_CONF_DIR}/supervisor/conf.d:/etc/supervisor/conf.d
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"