version: "3"
services:
  web_dev:
    image: ijuniorfu/centos7-nginx-php
    privileged: true
    ports:
     - "80:80"
     - "443:443"
     - "2222:22"
     - "9527:9527"
    volumes:
      - ${HTDOCS_DIR}:/data/htdocs
      - ${CONF_DIR}/nginx/conf.d:/etc/nginx/conf.d
      - ${CONF_DIR}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${CONF_DIR}/php/php.ini:/etc/php.ini
      - ${CONF_DIR}/supervisor/conf.d:/etc/supervisor/conf.d
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - custom_net
networks:
  custom_net:
    external:
      name: app_net