version: "3"
services:
  web_dev:
    image: ijuniorfu/web_dev_ubuntu
    privileged: true
    ports:
      - "80:80"
      - "443:443"
      - "2222:22"
      - "9527:9527"
    volumes:
      - ${HTDOCS_DIR}:/data/htdocs
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - ./conf/php/cli/php.ini:/etc/php/7.4/cli/php.ini
      - ./conf/php/fpm/php.ini:/etc/php/7.4/fpm/php.ini
      - ./conf/php/fpm/php-fpm.conf:/etc/php/7.4/fpm/php-fpm.conf
      - ./conf/php/fpm/pool.d:/etc/php/7.4/fpm/pool.d
      - ./conf/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./conf/supervisor/conf.d:/etc/supervisor/conf.d
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"